// GENERATED by extension/build.mjs — do not edit by hand.
// The committed Chrome build that /clip offers curators for download.
// lib/extension/release.test.ts fails if this drifts from extension/.

export const clipperRelease = {
  "version": "0.1.0",
  "sources": {
    "background.js": "e9ea88ac622a4347a03797cc9b3e0020cefe72e08a8be00e0aa58b9edea92e93",
    "content.js": "64db1bccfbcbeab0af31c3362509b769f55b0ee69cd396d9335f1b52ebd3a97f",
    "fonts/OFL.txt": "c3c8402eec0e31dc9a76851235b1c02a0bb821488b2db8e35bcc2ab60ca8fc2b",
    "fonts/archivo.woff2": "8f704806dbedeaaeca334b11ec348bc3ac3a439d6431544b3afb54f534ee4967",
    "icons/icon-128.png": "756a7adbd7d7866d5f26c59100913a0f4d39c31d49d0654721a37df183f2e8f8",
    "icons/icon-16.png": "77b345a88dd45e1a67feb515e452d7c229cd0ffe49444bbac011dfcc2716984b",
    "icons/icon-32.png": "f6b7d83f9f27b07b248069a5de843ad8b9fc596a19ba6cb3b55a8c09c0e81739",
    "icons/icon-48.png": "2d34dbee66caa4d7089d4d23d0f0c26c1f28c345d8edc5c1988dfa6b9368d86a",
    "icons/icon-96.png": "93a279b12d66f1b7d7db4184f0ade076dd34a17487d8a669a479bb2edee9f4dd",
    "icons/toolbar-bone-16.png": "e980e6744aa471ea217909bcfcbb10c003a5e77dd3de62c3153dba99a3e2d0df",
    "icons/toolbar-bone-32.png": "dff878ec23ec23450ca6508951b11a45d5ba5c129bedbe7077174bc56cd57c13",
    "icons/toolbar-bone-48.png": "86d9c456b021058e49541b0510bf46ef06d121028416bad5fbac30e31080bbfe",
    "icons/toolbar-ink-16.png": "3342fc54222d835c569799a79a9802c0c842a89f5b2d35682003b31e7e20132f",
    "icons/toolbar-ink-32.png": "6ab78fd89bae57b20c65761ed516e3cfeee373d5f655186b7fb362c7fe417f33",
    "icons/toolbar-ink-48.png": "7f1bf562a32b32c50858a33d9e05c5045dcaa3d45dd6ce297887fc23f740b3b2",
    "icons/wordmark.svg": "a066016c641a6b53314a73c4d8a0b73f0a9bd14238056869e3220759e83e518b",
    "manifest.json": "83aaa8ba558b982cde21c0590caff0e19118f56ae1e6743b62c9d326cdb01228",
    "options.css": "a85086a04d61106d5ff93ef29fed54d9438d6d3d68617e390c34c709d7fa8937",
    "options.html": "8f9ad8e4072e63d1fbde7a6e2647706697251c027950033af1ae7a08b1cc0b00",
    "options.js": "cfc1f6be358e2d86539ff01601c7aa74f50da7af19cfe60237aba16cc49656c1",
    "panel.css": "df9194f4b554269f2332951812a68b127ecb1afba7fded7584bb83c34d03a15a",
    "panel.html": "cbf7e3791a203f705981b49c5cc67241bf595b7d6e8a9ccd0067644779ed1107",
    "panel.js": "b5d77019db41811c194471c8af8fcd73314eb89670938ba590a6de9e83f802f0",
    "popup.css": "82fd7c1e7572e8c4c3fe30943122fe8cff87ea34d43c54761f720562f3893193",
    "popup.html": "ccbe1a8841038421ca7fb2c716922d527b0c7426f3d79596ddcb23c0e43e2d0b",
    "popup.js": "dcca89df2e776bc446b21421a2dda8612d3fd39f4381c6a62905e000ad6c2f21",
    "scheme.html": "f4653f91f5c7d2d45fe8a3b324718430fe9f540dfad96f9816e923b9ad98540e",
    "scheme.js": "836c980f2140db9756591a0f8045d00b4ace0f2f25ddf1487875dfd812cfa97c",
    "ui.css": "2d62366e851c6a4ef9e7e11817941ab6ef08353cd6870b2a2217aa30053190d8",
    "ui.js": "6071faf4be65b7b9e2816a6b1ca793bd0d6e069802424026a3a59fc9b031771d"
  }
} as const;
